# Generated by Django 3.2.9 on 2022-04-23 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['color'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
            ],
            options={
                'ordering': (['manufacturer'],),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('image', models.CharField(max_length=1000)),
                ('image1', models.CharField(max_length=1000)),
                ('image2', models.CharField(max_length=1000)),
                ('bio', models.CharField(default='Sobre medidas', max_length=100)),
                ('offert', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=1)),
                ('category', models.ManyToManyField(default='Cortinas', to='products.Category')),
                ('color', models.ManyToManyField(to='products.Color')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.manufacturer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
