# Generated by Django 3.2.9 on 2022-04-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('bio', models.CharField(default='Sobre medidas', max_length=100)),
                ('offert', models.BooleanField(default=False)),
                ('color', models.ManyToManyField(to='products.Color')),
            ],
        ),
    ]
