# Generated by Django 3.2.9 on 2022-04-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://persianashorizonte.com/wp-content/uploads/2019/02/Screen-Blanco-2.jpg', max_length=1000),
            preserve_default=False,
        ),
    ]
