# Generated by Django 3.2.9 on 2022-04-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['manufacturer']},
        ),
    ]
