# Generated by Django 3.2.9 on 2022-04-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.CharField(default='https://tuissco.vteximg.com.br/arquivos/ids/179908-1000-1000/cortina_sheer_elegance_oxford_beige_perlado_1.jpg?v=637683086571900000', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.CharField(default='https://tuissco.vteximg.com.br/arquivos/ids/179908-1000-1000/cortina_sheer_elegance_oxford_beige_perlado_1.jpg?v=637683086571900000', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
